steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/profound-alcove-441603-e8/flaskhelloworldapp', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/profound-alcove-441603-e8/flaskhelloworldapp']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'flaskhelloworldapp', '--image', 'gcr.io/profound-alcove-441603-e8/flaskhelloworldapp', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated', '--port', '80']
images:
- gcr.io/profound-alcove-441603-e8/flaskhelloworldapp
options:
  logging: CLOUD_LOGGING_ONLY
